### ISSUE TITLE
Support multiple keyboards

### ISSUE THREAD

**Issue by askvictor** [jarusll/keydogger#1]
I use a laptop, but this is often docked where it uses an external keyboard. The internal and external keyboards have different event paths. It would be great to be able to specify multiple keyboards.

**Comment by jarusll** [comment]
Can be solved using 2 keyboard paths specified by env vars. It would also solve implicit keyboard path as currently it's defined as a macro. 

Regarding error handling when you disconnect the external keyboard and the device file is unavailable, the program would be fine as long as there's one keyboard path to read from.

Good issue.

**Comment by jarusll** [comment]
The solution I proposed was overengineered. Keydogger is designed to handle 1 keyboard at a time. Keyboard paths can be specified using `KEYDOGGER_KEYBOARD` env variable. You can just `sudo keydogger restart` with a different keyboard path.
